steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - wiki_film_scraper
  - --region=us-east1
  - --source=.
  - --trigger-http
  - --runtime=RUNTIME

options:
  logging: CLOUD_LOGGING_ONLY